Scope Policy To Exact KMS Key
terraform-ibm-modules/terraform-ibm-appid pull request #270
Opened 2024-12-30 07:24 UTC by Vipin654

### Description

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [x] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

Scope Policy to Exact KMS Key

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

2024-12-30 07:25 UTC, Vipin654 commented
/run pipeline

2025-01-09 09:08 UTC, Vipin654 commented
/run pipeline

2025-01-10 10:06 UTC, Ak-sky commented
@Vipin654, in PR template
- please update the description
- link git issue
and
- Paste the screenshot in the comment and the reason why skipping upgrade test
- While commiting the code, provide commmit message in the format `<ty­pe>: <de­scr­ipt­ion>`, in this case 
`feat: Scope Policy To Exact KMS Key`. This helps in module release generation.

2025-01-10 18:00 UTC, Ak-sky requested changes
See comment https://github.com/terraform-ibm-modules/terraform-ibm-appid/pull/270#issuecomment-2582268088.

2025-01-15 05:12 UTC, Vipin654 commented
@Ak-sky UPGRADE test has to be skipped because Auth Policy will be destroyed and re-created which is a breaking change. I have Pasted screenshot for your reference.
<img width="1707" alt="Screenshot 2025-01-15 at 10 40 51 AM" src="https://github.com/user-attachments/assets/c477aba7-9b42-4705-b825-a4e9a176fa3f" />

2025-01-15 05:13 UTC, Vipin654 commented
/run pipeline

2025-01-16 07:30 UTC, Ak-sky commented on main.tf
> +  source_resource_group_id = var.resource_group_id
is there a reason we are scoping the source to resource group and not instance guid?

2025-01-16 07:35 UTC, Ak-sky commented on main.tf
> +  description              = "Allow all AppID instances in the given resource group reader access to KMS instance ${var.existing_kms_instance_guid}"
Description should be like this if source is scoped to resource group id.
```suggestion
  description              = "Allow all AppID instances in the given resource group ${var.resource_group_id} to read the ${local.kms_service} key ${local.kms_key_id} from instance ${var.existing_kms_instance_guid}"
```

2025-01-17 09:21 UTC, ocofaigh commented on main.tf
> +  source_resource_group_id = var.resource_group_id
@Ak-sky The auth policy has to exist before the instance. - so it cant be scoped to instance ID (same as all modules that support KMS)

2025-01-17 10:55 UTC, Vipin654 commented on main.tf
> +  description              = "Allow all AppID instances in the given resource group reader access to KMS instance ${var.existing_kms_instance_guid}"
Description has been changed.

2025-01-17 11:00 UTC, Vipin654 commented
/run pipeline

2025-01-18 09:54 UTC, Ak-sky submitted a review, later dismissed

2025-01-20 10:36 UTC, ocofaigh commented on main.tf
> +  count   = var.kms_key_crn != null ? 1 : 0
This is going to be a problem if user creates KMS key in same terraform code as this module. You should never use a computed value in a `count` like this, because if user tried to create the key in same terraform state as the AppID module, it will fail saying cannot use count on a computed resource.
Instead you should use the boolean variable `kms_encryption_enabled`

2025-01-20 10:36 UTC, ocofaigh commented on main.tf
> +  count   = var.kms_key_crn != null ? 1 : 0
If we had another example in this module which created the key, it would have caught this bug. But in the fscloud example we use existing key, so hence test did not fail.

2025-01-20 10:36 UTC, ocofaigh requested changes
see comment, there is a bug in count logic

2025-01-20 10:58 UTC, Vipin654 commented
/run pipeline

2025-01-20 11:06 UTC, Vipin654 commented on main.tf
> +  count   = var.kms_key_crn != null ? 1 : 0
Change has been implemented. Thanks @ocofaigh

2025-01-20 18:19 UTC, ocofaigh approved these changes

2025-01-20 18:19 UTC, merged

2025-01-20 18:20 UTC, terraform-ibm-modules-ops commented
:tada: This PR is included in version 1.3.0 :tada:

The release is available on [GitHub release](https://github.com/terraform-ibm-modules/terraform-ibm-appid/releases/tag/v1.3.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: